db:
  image: mysql
  volumes:
    - /data/redmine-db:/var/lib/mysql
    - /data/redmine-db-init:/docker-entrypoint-initdb.d
  environment:
    - MYSQL_ROOT_PASSWORD=mysql123
    - MYSQL_DATABASE=redmine
    - MYSQL_USER=redmine
    - MYSQL_PASSWORD=redmine
    - MYSQL_ALLOW_EMPTY_PASSWORD=no
  
redmine:
  image: redmine
  volumes:
    - /data/redmine/files:/usr/src/redmine/files
    - /data/redmine/plugins:/usr/src/redmine/plugins
  ports:
    - 52080:3000
  links:
    - db:mysql
  environment:
    - REDMINE_NO_DB_MIGRATE=1
